name: pegylation
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - gromacs
  - jupyterlab
  - ipywidgets
  - nglview
  - git
  - pip:
      - git+https://github.com/marrink-lab/polyply_1.0.git
      - Pras-Server==1.2.1
      - cgsmiles
      - GromacsWrapper
      - mdtraj
      - PyCifRW
